version: '3'

services:
  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build: 
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install -y && node src/index.js"
    restart: always
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    depends_on:
      - db

networks: 
  node-network:
    driver: bridge
